language: node_js
dist: precise

node_js:
    - '7'

before_install:
    - 'curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.28.1'

before_script:
    - 'npm run clean && npm run lint && npm run build'

after_success:
    - 'npm run coverage'
